name: Go Test Pipeline

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - "**.md"

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...
